name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
    - add_ci_cd
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Source the env
      run: source start.sh

    - name: Build the images
      run: bash build.sh

    - name: Start Local Cluster
      run: docker compose -f "local-cluster.yaml" up -d --build

    - name: Run tests
      run: |
        docker run --rm \
        --network spark-delta-plateform_default \
        --name unit-tests-job \
        --volume ./shared-vol/:/opt/workspace \
        --volume ./shared-vol/.ivy2:/root/.ivy2 \
        -it oussamabennasr/spark-delta-plateform:0.0.1 \
        pytest

    - name: Stop containers
      if: always()
      run: docker compose -f "local-cluster.yaml" down
