name: Unit Tests

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

jobs:
  ci-cd:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      shared-dir: ./shared-vol
      spark-worker-cores: 2

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build the images
      run: bash build.sh

    - name: Start Local Cluster
      run: docker compose -f "local-cluster.yaml" up -d
      env:
        SHARED_DIR: ${{env.shared-dir}}
        SPARK_WORKER_CORE: ${{env.spark-worker-core}}

    - name: Run tests
      run: |
        docker run --rm \
          --network spark-delta-plateform_default \
          --name unit-tests-job \
          --volume ./shared-vol/:/opt/workspace \
          --volume ./shared-vol/.ivy2:/root/.ivy2 \
          oussamabennasr/spark-delta-plateform:0.0.1 \
          pytest

    - name: Stop containers
      if: always()
      run: docker compose -f "local-cluster.yaml" down
      env:
        SHARED_DIR: ${{env.shared-dir}}
        SPARK_WORKER_CORE: ${{env.spark-worker-core}}

